_type: export
__export_format: 4
__export_date: 2023-10-24T14:29:35.092Z
__export_source: insomnia.desktop.app:v2023.5.8
resources:
  - _id: req_eb568b58761e47f0bbb2855c4b984830
    parentId: wrk_0e3b2974ff7f4f3eb31fbcad28321081
    modified: 1698151979784
    created: 1698151954890
    url: http://localhost:3000/api/get-population
    name: Get Cities and Residents from DB
    description: ""
    method: GET
    body: {}
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/2023.5.8
    authentication: {}
    metaSortKey: -1698151954890
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: wrk_0e3b2974ff7f4f3eb31fbcad28321081
    parentId: null
    modified: 1698151922524
    created: 1698151922524
    name: WizardsDev.yaml
    description: ""
    scope: design
    _type: workspace
  - _id: req_ad492356ede2470d96791faee1b4b84f
    parentId: wrk_0e3b2974ff7f4f3eb31fbcad28321081
    modified: 1698151951241
    created: 1698151929488
    url: http://localhost:3000/api/create-population
    name: Create Cities and Residents in DB
    description: ""
    method: POST
    body: {}
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/2023.5.8
    authentication: {}
    metaSortKey: -1698151929488
    isPrivate: false
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_16a7b18898e7cbc2e87c4cc4297606da1e32b59e
    parentId: wrk_0e3b2974ff7f4f3eb31fbcad28321081
    modified: 1698151922528
    created: 1698151922528
    name: Base Environment
    data: {}
    dataPropertyOrder: null
    color: null
    isPrivate: false
    metaSortKey: 1698151922528
    _type: environment
  - _id: jar_16a7b18898e7cbc2e87c4cc4297606da1e32b59e
    parentId: wrk_0e3b2974ff7f4f3eb31fbcad28321081
    modified: 1698151922530
    created: 1698151922530
    name: Default Jar
    cookies: []
    _type: cookie_jar
  - _id: spc_8bd43ca5a4cd47b283d3311556e732f1
    parentId: wrk_0e3b2974ff7f4f3eb31fbcad28321081
    modified: 1698151922527
    created: 1698151922527
    fileName: New Document
    contents: ""
    contentType: yaml
    _type: api_spec
