version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wizardsDevUser
      POSTGRES_PASSWORD: wizardsDevPass
      POSTGRES_DB: wizardsDevDb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
